env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides:
  - files:
      - "**/*.test.js"
      - "**/*.test.jsx"
    env:
      jest: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - never
